//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_new.ErrorManager
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Template_new.ErrorManager.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{A}&quot;.
        /// </summary>
        internal static string QIMS0000 {
            get {
                return ResourceManager.GetString("QIMS0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{A}&quot; cannot be left empty..
        /// </summary>
        internal static string QIMS0001 {
            get {
                return ResourceManager.GetString("QIMS0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Code &quot;{A}&quot; has been saved successfully..
        /// </summary>
        internal static string QIMS00014 {
            get {
                return ResourceManager.GetString("QIMS00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line  Code &quot;{A}&quot; Insertion Failed..
        /// </summary>
        internal static string QIMS00015 {
            get {
                return ResourceManager.GetString("QIMS00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line  Code &quot;{A}&quot; updated successfully..
        /// </summary>
        internal static string QIMS00016 {
            get {
                return ResourceManager.GetString("QIMS00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line  Code &quot;{A}&quot; updation failed..
        /// </summary>
        internal static string QIMS00017 {
            get {
                return ResourceManager.GetString("QIMS00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line  Code &quot;{A}&quot; already exists..
        /// </summary>
        internal static string QIMS00018 {
            get {
                return ResourceManager.GetString("QIMS00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Valid &quot;{A}&quot;.
        /// </summary>
        internal static string QIMS0002 {
            get {
                return ResourceManager.GetString("QIMS0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{A}&quot; can contain only alphabets..
        /// </summary>
        internal static string QIMS0003 {
            get {
                return ResourceManager.GetString("QIMS0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{A}&quot; can contain only text, no special characters are allowed.
        /// </summary>
        internal static string QIMS0004 {
            get {
                return ResourceManager.GetString("QIMS0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{A}&quot; can contain only numbers, no special characters and alphabets are allowed..
        /// </summary>
        internal static string QIMS0005 {
            get {
                return ResourceManager.GetString("QIMS0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{A}&quot; can contain only date and time..
        /// </summary>
        internal static string QIMS0006 {
            get {
                return ResourceManager.GetString("QIMS0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{A}&quot; already exist..
        /// </summary>
        internal static string QIMS0007 {
            get {
                return ResourceManager.GetString("QIMS0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Specific Record has been updated by someone, Please ensure and update again..
        /// </summary>
        internal static string QIMS0008 {
            get {
                return ResourceManager.GetString("QIMS0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Code &quot;{A}&quot; has been saved successfully..
        /// </summary>
        internal static string QIMS0009 {
            get {
                return ResourceManager.GetString("QIMS0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift  Code &quot;{A}&quot; Insertion Failed..
        /// </summary>
        internal static string QIMS0010 {
            get {
                return ResourceManager.GetString("QIMS0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift  Code &quot;{A}&quot; updated successfully..
        /// </summary>
        internal static string QIMS0011 {
            get {
                return ResourceManager.GetString("QIMS0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift  Code &quot;{A}&quot; updation failed..
        /// </summary>
        internal static string QIMS0012 {
            get {
                return ResourceManager.GetString("QIMS0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift  Code &quot;{A}&quot; already exists..
        /// </summary>
        internal static string QIMS0013 {
            get {
                return ResourceManager.GetString("QIMS0013", resourceCulture);
            }
        }
    }
}
